// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi3bJWs_J6G7XUK6vxbdcI_lD9ooa6bsA',
    appId: '1:919200129134:android:4fca1b7a91f4ebab32c67f',
    messagingSenderId: '919200129134',
    projectId: 'tungar-todo',
    databaseURL: 'https://tungar-todo-default-rtdb.firebaseio.com',
    storageBucket: 'tungar-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY0dnmWFVyzFJO6dqBO1ehBwvVAbd0VSA',
    appId: '1:919200129134:ios:d695f4458165b18532c67f',
    messagingSenderId: '919200129134',
    projectId: 'tungar-todo',
    databaseURL: 'https://tungar-todo-default-rtdb.firebaseio.com',
    storageBucket: 'tungar-todo.appspot.com',
    androidClientId: '919200129134-r488qfgsard8uu8p5raalnjcn3ifuhe1.apps.googleusercontent.com',
    iosClientId: '919200129134-ol40ahhp8v5e1k3ervv72irrvv792pbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.superTodo',
  );
}
